#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BAASBox.SampleApp.Droid.Resource", IsApplication=true)]

namespace BAASBox.SampleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XLabs.Platform.Resource.String.ApplicationName = global::BAASBox.SampleApp.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::BAASBox.SampleApp.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::BAASBox.SampleApp.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::BAASBox.SampleApp.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::BAASBox.SampleApp.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::BAASBox.SampleApp.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::BAASBox.SampleApp.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::BAASBox.SampleApp.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::BAASBox.SampleApp.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::BAASBox.SampleApp.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::BAASBox.SampleApp.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::BAASBox.SampleApp.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::BAASBox.SampleApp.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::BAASBox.SampleApp.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::BAASBox.SampleApp.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::BAASBox.SampleApp.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::BAASBox.SampleApp.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::BAASBox.SampleApp.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::BAASBox.SampleApp.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::BAASBox.SampleApp.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::BAASBox.SampleApp.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::BAASBox.SampleApp.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::BAASBox.SampleApp.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::BAASBox.SampleApp.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::BAASBox.SampleApp.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::BAASBox.SampleApp.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::BAASBox.SampleApp.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::BAASBox.SampleApp.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::BAASBox.SampleApp.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::BAASBox.SampleApp.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::BAASBox.SampleApp.Droid.Resource.Style.CalendarTitle;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::BAASBox.SampleApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::BAASBox.SampleApp.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::BAASBox.SampleApp.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::BAASBox.SampleApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int calendar_highlighted_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int calendar_inactive_month_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_selected_day_bg = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_active = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_inactive = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_selected = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int calendar_text_selector = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_unselectable = 2131099658;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int calendar_grid = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int calendar_view = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int left_arrow = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int right_arrow = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int title = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int simple = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int day_name_format = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int full_date_format = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int invalid_date = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int month_name_format = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CalendarCell = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_CalendarDate = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell_DayHeader = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CalendarTitle = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
